/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SC_ProcessExecution } from "./SC_ProcessExecution";
export type { SC_SupplyChain } from "./SC_SupplyChain";
