/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RA_0Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "SubChoreography_1sp0n7o"
      | "bond"
      | "enact"
      | "participants"
      | "setbond"
      | "setweeklyRent"
      | "tokenState"
      | "weeklyRent"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "SubChoreography_1sp0n7o",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "bond", values?: undefined): string;
  encodeFunctionData(functionFragment: "enact", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "participants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setbond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setweeklyRent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "weeklyRent",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "SubChoreography_1sp0n7o",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enact", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setbond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setweeklyRent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenState", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weeklyRent", data: BytesLike): Result;
}

export interface RA_0 extends BaseContract {
  connect(runner?: ContractRunner | null): RA_0;
  waitForDeployment(): Promise<this>;

  interface: RA_0Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  SubChoreography_1sp0n7o: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  bond: TypedContractMethod<[], [bigint], "view">;

  enact: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  participants: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  setbond: TypedContractMethod<[_bond: BigNumberish], [void], "nonpayable">;

  setweeklyRent: TypedContractMethod<
    [_weeklyRent: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenState: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  weeklyRent: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "SubChoreography_1sp0n7o"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bond"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "enact"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "participants"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "setbond"
  ): TypedContractMethod<[_bond: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setweeklyRent"
  ): TypedContractMethod<[_weeklyRent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenState"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "weeklyRent"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
