/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as scProcessExecutionSol from "./SC_ProcessExecution.sol";
export type { scProcessExecutionSol };
