/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SC_ProcessExecution__factory } from "./SC_ProcessExecution__factory";
export { SC_SupplyChain__factory } from "./SC_SupplyChain__factory";
