/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as raProcessExecutionSol from "./RA_ProcessExecution.sol";
export type { raProcessExecutionSol };
