/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RA_ProcessExecutionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bond"
      | "enact"
      | "participants"
      | "setWeeklyRent"
      | "tokenState"
      | "weeklyRent"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "bond", values?: undefined): string;
  encodeFunctionData(functionFragment: "enact", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "participants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWeeklyRent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "weeklyRent",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "bond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enact", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWeeklyRent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenState", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weeklyRent", data: BytesLike): Result;
}

export interface RA_ProcessExecution extends BaseContract {
  connect(runner?: ContractRunner | null): RA_ProcessExecution;
  waitForDeployment(): Promise<this>;

  interface: RA_ProcessExecutionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bond: TypedContractMethod<[], [bigint], "view">;

  enact: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  participants: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  setWeeklyRent: TypedContractMethod<
    [_weeklyRent: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenState: TypedContractMethod<[], [bigint], "view">;

  weeklyRent: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bond"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "enact"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "participants"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "setWeeklyRent"
  ): TypedContractMethod<[_weeklyRent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenState"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "weeklyRent"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
