/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as imProcessExecutionSol from "./IM_ProcessExecution.sol";
export type { imProcessExecutionSol };
