/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IM_ProcessExecution",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IM_ProcessExecution__factory>;
    getContractFactory(
      name: "PH_ProcessExecution",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PH_ProcessExecution__factory>;
    getContractFactory(
      name: "PIZZA_ProcessExecution",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PIZZA_ProcessExecution__factory>;
    getContractFactory(
      name: "RA_ProcessExecution",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RA_ProcessExecution__factory>;
    getContractFactory(
      name: "SC_ProcessExecution",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SC_ProcessExecution__factory>;

    getContractAt(
      name: "IM_ProcessExecution",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IM_ProcessExecution>;
    getContractAt(
      name: "PH_ProcessExecution",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PH_ProcessExecution>;
    getContractAt(
      name: "PIZZA_ProcessExecution",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PIZZA_ProcessExecution>;
    getContractAt(
      name: "RA_ProcessExecution",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RA_ProcessExecution>;
    getContractAt(
      name: "SC_ProcessExecution",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SC_ProcessExecution>;

    deployContract(
      name: "IM_ProcessExecution",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IM_ProcessExecution>;
    deployContract(
      name: "PH_ProcessExecution",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PH_ProcessExecution>;
    deployContract(
      name: "PIZZA_ProcessExecution",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PIZZA_ProcessExecution>;
    deployContract(
      name: "RA_ProcessExecution",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RA_ProcessExecution>;
    deployContract(
      name: "SC_ProcessExecution",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SC_ProcessExecution>;

    deployContract(
      name: "IM_ProcessExecution",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IM_ProcessExecution>;
    deployContract(
      name: "PH_ProcessExecution",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PH_ProcessExecution>;
    deployContract(
      name: "PIZZA_ProcessExecution",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PIZZA_ProcessExecution>;
    deployContract(
      name: "RA_ProcessExecution",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RA_ProcessExecution>;
    deployContract(
      name: "SC_ProcessExecution",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SC_ProcessExecution>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
