/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as pizzaProcessExecutionSol from "./PIZZA_ProcessExecution.sol";
export type { pizzaProcessExecutionSol };
