/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as phProcessExecutionSol from "./PH_ProcessExecution.sol";
export type { phProcessExecutionSol };
