/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PIZZA_PizzaDelivery } from "./PIZZA_PizzaDelivery";
export type { PIZZA_ProcessExecution } from "./PIZZA_ProcessExecution";
